// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity >=0.8.0;

interface IConvexAMO_Old {
  function DEFAULT_ADMIN_ROLE (  ) external view returns ( bytes32 );
  function FRAX3CRVInVault (  ) external view returns ( uint256 );
  function acceptOwnership (  ) external;
  function borrowedCollatBalance (  ) external view returns ( int256 );
  function borrowed_collat_historical (  ) external view returns ( int256 );
  function burnFRAX ( uint256 frax_amount ) external;
  function burnFXS ( uint256 amount ) external;
  function burned_frax_historical (  ) external view returns ( int256 );
  function claimRewardsFRAX3CRV (  ) external;
  function claimRewards_cvxCRV ( bool stake ) external;
  function collatDollarBalance (  ) external view returns ( uint256 );
  function collat_borrow_cap (  ) external view returns ( int256 );
  function convergence_window (  ) external view returns ( uint256 );
  function custodian_address (  ) external view returns ( address );
  function custom_floor (  ) external view returns ( bool );
  function depositFRAX3CRV ( uint256 _metapool_lp_in ) external;
  function discount_rate (  ) external view returns ( uint256 );
  function fraxDiscountRate (  ) external view returns ( uint256 );
  function fraxFloor (  ) external view returns ( uint256 );
  function frax_floor (  ) external view returns ( uint256 );
  function getRoleAdmin ( bytes32 role ) external view returns ( bytes32 );
  function getRoleMember ( bytes32 role, uint256 index ) external view returns ( address );
  function getRoleMemberCount ( bytes32 role ) external view returns ( uint256 );
  function giveCollatBack ( uint256 amount ) external;
  function grantRole ( bytes32 role, address account ) external;
  function hasRole ( bytes32 role, address account ) external view returns ( bool );
  function initialize ( address _frax_contract_address, address _fxs_address, address _collateral_address, address _creator_address, address _custodian_address, address _timelock_address, address _frax3crv_metapool_address, address _pool_address ) external;
  function iterate (  ) external view returns ( uint256, uint256, uint256, uint256 );
  function liq_slippage_3crv (  ) external view returns ( uint256 );
  function max_frax_outstanding (  ) external view returns ( int256 );
  function metapoolDeposit ( uint256 _frax_amount, uint256 _collateral_amount ) external returns ( uint256 metapool_LP_received );
  function metapoolWithdrawAndConvert3pool ( uint256 _metapool_lp_in ) external;
  function metapoolWithdrawFrax ( uint256 _metapool_lp_in, bool burn_the_frax ) external returns ( uint256 frax_received );
  function min_cr (  ) external view returns ( uint256 );
  function mintRedeemPart1 ( uint256 frax_amount ) external;
  function mintRedeemPart2 (  ) external;
  function mintedBalance (  ) external view returns ( int256 );
  function minted_frax_historical (  ) external view returns ( int256 );
  function nominateNewOwner ( address _owner ) external;
  function nominatedOwner (  ) external view returns ( address );
  function override_collat_balance (  ) external view returns ( bool );
  function override_collat_balance_amount (  ) external view returns ( uint256 );
  function owner (  ) external view returns ( address );
  function recoverERC20 ( address tokenAddress, uint256 tokenAmount ) external;
  function renounceRole ( bytes32 role, address account ) external;
  function returned_collat_historical (  ) external view returns ( int256 );
  function revokeRole ( bytes32 role, address account ) external;
  function setCollatBorrowCap ( int256 _collat_borrow_cap ) external;
  function setConvergenceWindow ( uint256 _window ) external;
  function setCustodian ( address _custodian_address ) external;
  function setCustomFloor ( bool _state, uint256 _floor_price ) external;
  function setDiscountRate ( bool _state, uint256 _discount_rate ) external;
  function setMaxFraxOutstanding ( int256 _max_frax_outstanding ) external;
  function setMinimumCollateralRatio ( uint256 _min_cr ) external;
  function setOverrideCollatBalance ( bool _state, uint256 _balance ) external;
  function setSlippages ( uint256 _liq_slippage_3crv, uint256 _slippage_metapool ) external;
  function setTimelock ( address new_timelock ) external;
  function set_discount (  ) external view returns ( bool );
  function showAllocations (  ) external view returns ( uint256[11] memory return_arr );
  function showRewards (  ) external view returns ( uint256[8] memory return_arr );
  function slippage_metapool (  ) external view returns ( uint256 );
  function stakeCVX ( uint256 _cvx_in ) external;
  function timelock_address (  ) external view returns ( address );
  function totalInvested (  ) external view returns ( int256 );
  function withdrawAndUnwrapFRAX3CRV ( uint256 amount, bool claim ) external;
  function withdrawCVX ( uint256 cvx_amt, bool claim ) external;
  function withdrawRewards ( uint256 crv_amt, uint256 cvx_amt, uint256 cvxCRV_amt, uint256 fxs_amt ) external;
}
