// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity >=0.8.0;

interface I3pool {
  function A() external view returns (uint256);
  function A_precise() external view returns (uint256);
  function dynamic_fee(int128 i, int128 j) external view returns (uint256);
  function balances(uint256 i) external view returns (uint256);
  function get_virtual_price() external view returns (uint256);
  function calc_token_amount(uint256[3] memory _amounts, bool is_deposit) external view returns (uint256);
  function add_liquidity(uint256[3] memory _amounts, uint256 _min_mint_amount) external returns (uint256);
  function add_liquidity(uint256[3] memory _amounts, uint256 _min_mint_amount, bool _use_underlying) external returns (uint256);
  function get_dy(int128 i, int128 j, uint256 dx) external view returns (uint256);
  function get_dy_underlying(int128 i, int128 j, uint256 dx) external view returns (uint256);
  function exchange(int128 i, int128 j, uint256 dx, uint256 min_dy) external returns (uint256);
  function exchange_underlying(int128 i, int128 j, uint256 dx, uint256 min_dy) external returns (uint256);
  function remove_liquidity(uint256 _amount, uint256[3] memory _min_amounts) external returns (uint256[3] memory);
  function remove_liquidity(uint256 _amount, uint256[3] memory _min_amounts, bool _use_underlying) external returns (uint256[3] memory);
  function remove_liquidity_imbalance(uint256[3] memory _amounts, uint256 _max_burn_amount) external returns (uint256);
  function remove_liquidity_imbalance(uint256[3] memory _amounts, uint256 _max_burn_amount, bool _use_underlying) external returns (uint256);
  function calc_withdraw_one_coin(uint256 _token_amount, int128 i) external view returns (uint256);
  function remove_liquidity_one_coin(uint256 _token_amount, int128 i, uint256 _min_amount) external returns (uint256);
  function remove_liquidity_one_coin(uint256 _token_amount, int128 i, uint256 _min_amount, bool _use_underlying) external returns (uint256);
  function ramp_A(uint256 _future_A, uint256 _future_time) external;
  function stop_ramp_A() external;
  function commit_new_fee(uint256 new_fee, uint256 new_admin_fee, uint256 new_offpeg_fee_multiplier) external;
  function apply_new_fee() external;
  function revert_new_parameters() external;
  function commit_transfer_ownership(address _owner) external;
  function apply_transfer_ownership() external;
  function revert_transfer_ownership() external;
  function withdraw_admin_fees() external;
  function donate_admin_fees() external;
  function kill_me() external;
  function unkill_me() external;
  function set_aave_referral(uint256 referral_code) external;
  function set_reward_receiver(address _reward_receiver) external;
  function set_admin_fee_receiver(address _admin_fee_receiver) external;
  function coins(uint256 arg0) external view returns (address);
  function underlying_coins(uint256 arg0) external view returns (address);
  function admin_balances(uint256 arg0) external view returns (uint256);
  function fee() external view returns (uint256);
  function offpeg_fee_multiplier() external view returns (uint256);
  function admin_fee() external view returns (uint256);
  function owner() external view returns (address);
  function lp_token() external view returns (address);
  function initial_A() external view returns (uint256);
  function future_A() external view returns (uint256);
  function initial_A_time() external view returns (uint256);
  function future_A_time() external view returns (uint256);
  function admin_actions_deadline() external view returns (uint256);
  function transfer_ownership_deadline() external view returns (uint256);
  function future_fee() external view returns (uint256);
  function future_admin_fee() external view returns (uint256);
  function future_offpeg_fee_multiplier() external view returns (uint256);
  function future_owner() external view returns (address);
  function reward_receiver() external view returns (address);
  function admin_fee_receiver() external view returns (address);
}