// SPDX-License-Identifier: MIT
pragma solidity >=0.6.11;

interface IStkTruToken {
  function DELEGATION_TYPEHASH (  ) external view returns ( bytes32 );
  function DOMAIN_TYPEHASH (  ) external view returns ( bytes32 );
  function allowance ( address, address ) external view returns ( uint256 );
  function approve ( address spender, uint256 amount ) external returns ( bool );
  function balanceOf ( address ) external view returns ( uint256 );
  function checkpoints ( address, uint32 ) external view returns ( uint32 fromBlock, uint96 votes );
  function claim (  ) external;
  function claimOwnership (  ) external;
  function claimRestake ( uint256 extraStakeAmount ) external;
  function claimRewards ( address token ) external;
  function claimable ( address account, address token ) external view returns ( uint256 );
  function cooldown (  ) external;
  function cooldownTime (  ) external view returns ( uint256 );
  function decimals (  ) external pure returns ( uint8 );
  function decreaseAllowance ( address spender, uint256 subtractedValue ) external returns ( bool );
  function delegate ( address delegatee ) external;
  function delegateBySig ( address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s ) external;
  function delegates ( address ) external view returns ( address );
  function distributor (  ) external view returns ( address );
  function farmRewards ( address ) external view returns ( uint256 cumulativeRewardPerToken, uint256 totalClaimedRewards, uint256 totalFarmRewards );
  function feeToken (  ) external view returns ( address );
  function getCurrentVotes ( address account ) external view returns ( uint96 );
  function getPastTotalSupply ( uint256 blockNumber ) external view returns ( uint256 );
  function getPastVotes ( address account, uint256 blockNumber ) external view returns ( uint96 );
  function getPriorVotes ( address account, uint256 blockNumber ) external view returns ( uint96 );
  function increaseAllowance ( address spender, uint256 addedValue ) external returns ( bool );
  function initTotalSupplyCheckpoints (  ) external;
  function initalized (  ) external view returns ( bool );
  function initialize ( address _tru, address _tfusd, address _feeToken, address _distributor, address _liquidator ) external;
  function liquidator (  ) external view returns ( address );
  function name (  ) external pure returns ( string memory);
  function nextDistributionIndex (  ) external view returns ( uint32 );
  function nonces ( address ) external view returns ( uint256 );
  function numCheckpoints ( address ) external view returns ( uint32 );
  function owner (  ) external view returns ( address );
  function pauseStatus (  ) external view returns ( bool );
  function payFee ( uint256 amount, uint256 endTime ) external;
  function pendingOwner (  ) external view returns ( address );
  function receivedDuringCooldown ( address ) external view returns ( uint256 );
  function rounding (  ) external pure returns ( uint8 );
  function scheduledRewards ( uint256 ) external view returns ( uint64 timestamp, uint96 amount );
  function setCooldownTime ( uint256 newCooldownTime ) external;
  function setFeeToken ( address _feeToken ) external;
  function setLiquidator ( address _liquidator ) external;
  function setPauseStatus ( bool status ) external;
  function setPayerWhitelistingStatus ( address payer, bool status ) external;
  function setUnstakePeriodDuration ( uint256 newUnstakePeriodDuration ) external;
  function sortedScheduledRewardIndices ( uint256 ) external view returns ( uint32 );
  function stake ( uint256 amount ) external;
  function stakeSupply (  ) external view returns ( uint256 );
  function symbol (  ) external pure returns ( string memory );
  function tfusd (  ) external view returns ( address );
  function totalSupply (  ) external view returns ( uint256 );
  function transfer ( address recipient, uint256 amount ) external returns ( bool );
  function transferFrom ( address sender, address recipient, uint256 amount ) external returns ( bool );
  function transferOwnership ( address newOwner ) external;
  function tru (  ) external view returns ( address );
  function undistributedTfusdRewards (  ) external view returns ( uint256 );
  function unlockTime ( address account ) external view returns ( uint256 );
  function unstakable ( address staker ) external view returns ( uint256 );
  function unstake ( uint256 amount ) external;
  function unstakePeriodDuration (  ) external view returns ( uint256 );
  function whitelistedFeePayers ( address ) external view returns ( bool );
  function withdraw ( uint256 amount ) external;
}