// SPDX-License-Identifier: MIT
pragma solidity >=0.6.11;

interface ITrueFiPool2 {
  function TOLERATED_SLIPPAGE (  ) external view returns ( uint16 );
  function TOLERATED_STRATEGY_LOSS (  ) external view returns ( uint16 );
  function VERSION (  ) external view returns ( uint8 );
  function allowance ( address owner, address spender ) external view returns ( uint256 );
  function approve ( address spender, uint256 amount ) external returns ( bool );
  function averageExitPenalty ( uint256 from, uint256 to ) external pure returns ( uint256 );
  function balanceOf ( address account ) external view returns ( uint256 );
  function beneficiary (  ) external view returns ( address );
  function borrow ( uint256 amount ) external;
  function claimOwnership (  ) external;
  function claimableFees (  ) external view returns ( uint256 );
  function collectFees (  ) external;
  function creditAgency (  ) external view returns ( address );
  function creditValue (  ) external view returns ( uint256 );
  function currencyBalance (  ) external view returns ( uint256 );
  function decimals (  ) external view returns ( uint8 );
  function decreaseAllowance ( address spender, uint256 subtractedValue ) external returns ( bool );
  function deficitValue (  ) external view returns ( uint256 );
  function flush ( uint256 amount ) external;
  function increaseAllowance ( address spender, uint256 addedValue ) external returns ( bool );
  function initialize ( address _token, address _lender, address _safu, address __owner ) external;
  function integrateAtPoint ( uint256 x ) external pure returns ( uint256 );
  function isInitialized (  ) external view returns ( bool );
  function join ( uint256 amount ) external;
  function joiningFee (  ) external view returns ( uint256 );
  function lender (  ) external view returns ( address );
  function liquidExit ( uint256 amount ) external;
  function liquidExitPenalty ( uint256 amount ) external view returns ( uint256 );
  function liquidRatio (  ) external view returns ( uint256 );
  function liquidValue (  ) external view returns ( uint256 );
  function liquidate ( address loan ) external;
  function loansValue (  ) external view returns ( uint256 );
  function name (  ) external view returns ( string memory );
  function oracle (  ) external view returns ( address );
  function owner (  ) external view returns ( address );
  function pauseStatus (  ) external view returns ( bool );
  function pendingOwner (  ) external view returns ( address );
  function poolValue (  ) external view returns ( uint256 );
  function proFormaLiquidRatio ( uint256 amount ) external view returns ( uint256 );
  function pull ( uint256 minTokenAmount ) external;
  function reclaimDeficit ( address loan ) external;
  function repay ( uint256 currencyAmount ) external;
  function safu (  ) external view returns ( address );
  function setBeneficiary ( address newBeneficiary ) external;
  function setCreditAgency ( address _creditAgency ) external;
  function setJoiningFee ( uint256 fee ) external;
  function setOracle ( address newOracle ) external;
  function setPauseStatus ( bool status ) external;
  function setSafuAddress ( address _safu ) external;
  function singleBorrowerInitialize ( address _token, address _lender, address _safu, address __owner, string memory borrowerName, string memory borrowerSymbol ) external;
  function strategy (  ) external view returns ( address );
  function strategyValue (  ) external view returns ( uint256 );
  function switchStrategy ( address newStrategy ) external;
  function symbol (  ) external view returns ( string memory );
  function token (  ) external view returns ( address );
  function totalSupply (  ) external view returns ( uint256 );
  function transfer ( address recipient, uint256 amount ) external returns ( bool );
  function transferFrom ( address sender, address recipient, uint256 amount ) external returns ( bool );
  function transferOwnership ( address newOwner ) external;
  function utilization (  ) external view returns ( uint256 );
}
